kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-slave
spec:
  replicas: 1
  selector:
    component: spark-slave
  template:
    metadata:
      labels:
        component: spark-slave
    spec:
      containers:
        - name: spark-slave
          image: mjelen/spark:latest
          args: ["slave"]
